name: Transfer Build Files 1
 
on: 
  push: 
    branches: 
      - main 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout Repository 
      uses: actions/checkout@v2 
 
    - name: Setup SSH 
      uses: shimataro/ssh-key-action@v2 
      with: 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }} 
 
    - name: executing remote ssh commands using passwordss 
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.REMOTE_HOST }} 
        username: ${{ secrets.REMOTE_USERNAME }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        script: | 
            cd /home/ubuntu/TestNew2
            git pull origin main 
            cd all_in_docker 
            sudo docker-compose build 
            sudo docker-compose up -d backend 
            sudo docker-compose up -d frontend